openapi: 3.0.3
info:
  title: Tasks service API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      operationId: getAllTasks
      responses:
        "200":  
          description: A list of all tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GetTaskDto"
        "500":
          $ref: "#/components/errors/InternalServerError"
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskDto"
      responses:
        "201":
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
        "500":
          $ref: "#/components/errors/InternalServerError"
components:
  schemas:
    GetTaskDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string
        deadline:
          type: string
          format: date
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        weather:
          type: string
        user_id:
          type: string
      required:
        - name 
        - user_id
    CreateTaskDto:
      type: object
      properties:
        name: 
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        user_id:
          type: int
      required:
        - name
        - user_id
    Tag:
      type: object
      properties:
        name:
          type: string
      required: 
        - name
    Error:
      type: object 
      properties:
        error:
          type: string
      required:
        - string
  errors:
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error" 
