openapi: 3.0.3
info:
  title: Tasks service API
  version: 1.0.0

paths:
  /tasks:
    $ref: './paths/tasks.yaml#/~1tasks'
  /tasks/{id}:
    $ref: './paths/tasks.yaml#/~1tasks~1{id}'
  /auth/login:
    $ref: './paths/auth.yaml#/~1auth~1login'
  /auth/signup:
    $ref: './paths/auth.yaml#/~1auth~1signup'
  /auth/me:
    $ref: './paths/auth.yaml#/~1auth~1me'
  /auth/refresh:
    $ref: './paths/auth.yaml#/~1auth~1refresh'

components:
  schemas:
    $ref: './components/schemas.yaml'
  securitySchemes:
    $ref: './components/security.yaml#/BearerAuth'
  parameters:
    $ref: './components/parameters.yaml#/'
